name: CI cloud

on:
  push:
    paths:
      - cicd/**

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Run k6 cloud test
        uses: k6io/action@v0.1
        with:
          filename: cicd/cicd.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
        env:
          K6_CLOUD_PROJECT_ID: ${{ secrets.GRAFANA_PROJECT_ID }}
