name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  k6_load_test:
    if: ${{ github.event.label.name == 'run_load_test' }}
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: cicd/cicd.js
          flags: --out json=results.json
          
      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: results.json
